### ISSUE TITLE
host-device: specify device with pci address

### ISSUE THREAD

**Issue by zshi-redhat** [containernetworking/plugins#253]
Currently host-device plugin supports specifying devices with three properties: ``device``, ``hwaddr``, ``kernelpath``. This is to request another property called ``pciaddr``.

Benefit of having ``pciaddr`` support is when using host-device along with other metaPlugins such as Multus. It can parse and config the device with given ``pciaddr`` that passed from Multus (Multus has the ability to retrieve devices allocated from kubelet device plugin and pass ``pciaddr`` of that device to delegated plugins).

**Comment by s1061123** [comment]
I suppose we do not use 'pci address' for host-device identifier 

1. all network interface (i.e. host-device) is not pci device. 
For example, USB ethernet adapter does not have pci address, it has just USB port for identifier. So it is not enough for host-device.

1. current CNI spec does have kinds of abstraction in a good sense
Current CNI spec does not contain any hardware specific parameter and give good abstraction. I believe it provides multi platform support and we could keep it, I wish.

**Comment by jellonek** [comment]
IMO instead of extending `host-device` with this information software which is using this plugin should have detection of such case on its own side e.g. by looking if `/sys/class/net/DEVICE_NAME/device/subsystem` is link to `../../../../bus/pci` then resolving `/sys/class/net/DEVICE_NAME/device` symlink (that would be something like `../../../0000:02:00.0`) and skipping `../../../` prefix.

That's how i'm doing on my side of my CNI plugin calling handler.
