### ISSUE TITLE
Ghost IP addresses

### ISSUE THREAD

**Issue by remco011** [containernetworking/plugins#274]
During tests on a test cluster (four nodes, one master and three workers. Kubernetes version 1.12.5 deployed with Kubespray version 2.8.2) I sometimes experienced ghost IP addresses. IP addresses of docker containers remained pingable while the containers were already stopped running. The ghost IP addresses belonged to pods that had run on a node.

Ghost IP addresses on a node, for example node 2, were not pingable from the node itself. So in this example not from node 2, but were pingable from node 1, 3 and 4.

With the following method the content of the network namespace of a Docker containers can be seen:

pid=$(docker inspect -f '{{.State.Pid}}' ${container_id}) 
mkdir -p /var/run/netns/ 
ln -sfT /proc/$pid/ns/net /var/run/netns/$container_id 
 
ip netns exec "${container_id}" ip -s link

I'm not able to find an interface in a network namespace that belonged to the ghost IP address.

I use multus in combination with macvlan to create pods with two interfaces: eth0 = calico and net1 = multus+macvlan. IPAM plugin dhcp is used. A container with a dhcp server (https://hub.docker.com/r/joebiellik/dhcpd) is deployed with an additional multus+macvlan interface but with IPAM static plugin. To make the dhcp IPAM plugin work, /opt/cni/bin/dhcp is started with argument "daemon" on every worker node.

After deleting a pod, its IP address it received from the dhcp server on its multus+macvlan interface was still pingable. When killing the /opt/cni/bin/dhcp daemon process on the node, the ghost IP address disappears (doesn't reply to icmp requests anymore).

No change is seen in network namespaces or network namespaces related information in the /proc directory on the node that contained the ghost IP address, before and after the kill of the dhcp daemon.

At this moment I don't know what is causing the existence of ghost IP addresses in the cluster. Due to the fact the ghost IP address disappears when the dhcp daemon is killed makes the dhcp ipam plugin a suspect.

**Comment by dcbw** [comment]
Kubernetes does not immediately delete/cleanup the sandbox, it could be anywhere from 0 to 60+ seconds later. So I would expect the address might be available for a short period of time after the container itself goes away. But if it's 2+ minutes after the container is dead, then it would be an issue.

**Comment by remco011** [comment]
I ran some test scripts that created 10 containers and after 15 minutes deleted the 10 containers and created new ones again. I let this script run for a few hours. Another script was counting the pingable IP addresses in the same network range as the containers. I expected to see the number of pingable IP addresses grow with 10 when the containers are created, minus 10 when the containers are deleted and plus 10 again when 10 new containers are deployed again. What really happened was that the number of pingable IP addresses was not the same when 10 containers were running but increasing with small amounts.
The deletion and creation of the test containers is done by the script every 15 minutes. This is more than 2 minutes so I think it is an issue.

**Comment by jellonek** [comment]
To be fully sure that pod data (including networking part of pod sandbox) is properly garbage collected in the moment of pod deletion - please add `--grace-period=0` to `kubectl delete` parameters.
If ip is still accessible after deletion of pod with these parameter, that CAN be an issue, but also can be expected behavior of the particular implementation of CNI plugin. It's up to plugin how deletion is done on it's level, so some parts of configuration changing can be delegated from plugin binary to its control pane companion so in effect - it can be finished in plugin specific time.

In case of macvlan plugin this should be (afaik) done instantaneously so when deletion was called with `--grace-period=0` - when `kubectl` will finish ip should be already removed.

IDK precisely how that's handled on calico level, but for sure it delegates some part of network reconfiguration to its control pane part.
