### ISSUE TITLE
SBR: add check support

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#297]
Need to scope exactly what this would entail.

**Comment by squeed** [comment]
@plwhite

**Comment by plwhite** [comment]
Sorry for the delay - over-excitable mail filter ate my notification.

This might be tricky. SBR is a chained plugin that modifies the impact of the previous plugin. Taking bridge as an example, you might have a chain with bridge plugin setting up device and routes, then SBR changing routing. If you call CHECK on the bridge plugin it will have a fit (where did all its routes go?). Hence the worry is that the SBR plugin will break CHECK on the plugins before it.

The ideal would be that the bridge plugin either defers route checking to the SBR plugin, or better that the SBR plugin tells the bridge plugin which routing table to check. The latter would be easier, but there isn't a good way for the calling plugin to know, and it means that every calling plugin would have to somehow be told "these routes you created, they are now associated with routing table 123, not the default routing table". I can't see an easy way to do that without hacking about with interfaces in a horrible way.

Possible options might be:

1. Change the interfaces between plugins to accommodate just this one plugin in a horrible tail-wagging-dog mess. Let's not do that.

2. Change the standard plugins to all know if SBR is in use - so the bridge plugin (say) calls the SBR plugin to find that it should be using routing table 123. That feels like it might work quite well, but means non-standard plugins may not work properly with the SBR plugin.

3. Document it away by requiring that `disableCheck` be set if SBR is in use.

None of these are pretty. I'm torn between just pushing for 3 and doing some mix of 3 and 2.

@squeed what do you think?

**Comment by squeed** [comment]
Interesting, thanks for spelling this out. I wonder if there's a way for `bridge`, for example, to check that the routes exist in a fairly agnostic way? Can you think of one?

Ultimately, yes, you're right - `disableCheck` is the safety valve for this. And I really want `bridge` to have some form of route checking - routes being broken is a real-life thing we've seen in the wild.

**Comment by plwhite** [comment]
I think the issue is that the config has two plugins configured chained together and (from a quick code scan, let me know if I am wrong) the first plugin cannot know that the second plugin cannot tell that the second plugin is there. Hence it's hard (impossible?) for the first plugin to spot that the second plugin is present and has done something confusing. If I've misread that and the first plugin can tell, then it's probably not too hard to do something sensible.

Are there other precedents for a case like this where there are two plugins, and the behaviour of the second modifies the results of the first? There are other plugins that are always chained (tuning, firewall, portmap) but they are not so visible to the first plugin in this way.

More generally, there is probably a doc full of use cases for the CHECK command - do you have a link to that? I want to sanity check whether what I am doing really is solving those use cases.

**Comment by rajatchopra** [comment]
Is it possible to have the SBR be called at the end of all interface configurations? And not as a chain? Through multus, for example. Then SBR could discover and perform the route manipulations freely without CHECKs coming in the way + the global picture will help consolidate each of the tables.

This of course means that SBR be modified from what it is today.

**Comment by plwhite** [comment]
@rajatchopra I don't think it would be possible. You'd have to have some pretty complicated config so that the SBR plugin could figure out which interfaces it needed to change routes on. Even then, it wouldn't have access to the default route for the various interfaces; the existing model finds the default route by getting it out of the IPAM result that it has access to as a chained plugin. That could be resolved once we have the ability to configure a default route for each network, but it's some way off.

The bit that I am struggling with here is where exactly the CHECK gets called or what the use case is that it answers; I feel I'm probably missing something. @squeed, could you comment on that?

**Comment by squeed** [comment]
What is the difference between executing SBR once, and once per interface? They should sum to the same effect, right?

**Comment by Elegant996** [comment]
Another question might be when should it be executed. Many plugins such as `static` now allow for an IP to be defined at runtime. That means that `sbr` should not execute until after that IP is set, otherwise the plugin would have no effect.

**Comment by plwhite** [comment]
@squeed There are two problems here.

- SBR does not run once per interface for all interfaces; it runs for a subset of interfaces. At the moment, running it as a chained plugin means that it never needs to know the full list of which interfaces have SBR enabled, just that the one that is being done now needs to have it set up. It's a bit tedious operationally if you have to configure that list, because you now have (in Kubernetes with multus) SBR with a different network attachment definition depending on which other networks it is in use with, or else have to plumb through extra arguments.

- The default route gets tricky. When SBR gets called to create a new routing table and move all the routes on an interface into it, it needs to know the default gateway to create a default route. The only place it can get that is from the IPAM result for the interface. I don't think it can get all of the default gateways for all of the interfaces, just for the one it is currently processing.

None of this is insurmountable, but it makes things a little more fiddly.

**Comment by plwhite** [comment]
Stepping back a bit, I am getting my head round CHECK function, and reading the spec trying to figure out what we can do. I think there is something here, just not 100% sure what yet.
