### ISSUE TITLE
ipam.ExecDel doesn't actually delete

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#303]
It seems we failed to actually set CNI_COMMAND to DEL. Every single plugin works around this.

We should fix `ipam.ExecDel`, then remove the workaround in all the plugins.

**Comment by mars1024** [comment]
I think the root cause is not here, but in **Delegation funcs** (DelegateAdd, DelegateDel ...) in cni/invoke, so I think it's better to let Delegation func to override CNI_COMMAND automatically, this is the fix PR [https://github.com/containernetworking/cni/pull/663](https://github.com/containernetworking/cni/pull/663) and related issuse [https://github.com/containernetworking/cni/issues/665](https://github.com/containernetworking/cni/issues/665), if you have time, please take a look at, thanks a lot ~ @squeed @dcbw @mccv1r0
