### ISSUE TITLE
all current configuration options of the args cni json

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/plugins#361]
With this configuration I can request an ip address. What other options are all available in args.cni?

```
{
  "name": "test-sample",
  "type": "sample",
  "MyAwesomeFlag": false,
  "AnotherAwesomeArg": "blabla1",
  "ipam": {
    "type": "host-local",
    "subnet": "192.168.122.0/24"
  },
  "args": {
    "cni": { "ips": ["192.168.122.177"] }
  }
}
```

**Comment by smarkm** [comment]
How you got this configuration @f1-outsourcing ? You can find some help in `skel.CmdArgs`, I think you need self define and process the args if you just testing your own `sample` plugin 
```go
type CmdArgs struct {
	ContainerID string
	Netns       string
	IfName      string
	Args        string
	Path        string
	StdinData   []byte
}
```

**Comment by bboreham** [comment]
The args supported by the `host-local` plugin are described [here](https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local#supported-arguments).

**Comment by dcbw** [comment]
@f1-outsourcing args.cni is a freeform way of passing well-fromed information to plugins that is not part of the specification (because it's usually specific to plugins and thus not appropriate for the generic CNI specification). However some of the values passed are formalized in https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md .

But configs can also use 'args' to pass any information they like to a plugin, including plugin-specific arguments and data.
