### ISSUE TITLE
flannel /var/lib/cni/flannel/cid  not be removed if cni run failed

### ISSUE THREAD

**Issue by hongli-my** [containernetworking/plugins#426]
/var/lib/cni/flannel/xxx will leak if allocate ip failed.
1.https://github.com/containernetworking/plugins/blob/master/plugins/meta/flannel/flannel.go#L168 allocate ip failed,   
2. https://github.com/containernetworking/plugins/blob/master/plugins/meta/flannel/flannel.go#L164 will leak

maybe add `consumeScratchNetConf`  if  `invoke.DelegateAdd`  failed.

**Comment by hongli-my** [comment]
![image](https://user-images.githubusercontent.com/8597823/71051563-b9365700-2183-11ea-8ef3-759207ccd3c7.png)

**Comment by mars1024** [comment]
Yes, that's a problem, we need a `defer` to clean this.

**Comment by squeed** [comment]
I'm not so sure this is an issue - flannel just calls an ADD, and if ADD fails, then the delegated plugin should clean itself up.

What version are you using?

**Comment by mars1024** [comment]
The leak is not caused by delegated plugin but by flannel itself [https://github.com/containernetworking/plugins/blob/ec8f6c99d030bd75337ae8bfc62fc02cdc462528/plugins/meta/flannel/flannel.go#L164](https://github.com/containernetworking/plugins/blob/ec8f6c99d030bd75337ae8bfc62fc02cdc462528/plugins/meta/flannel/flannel.go#L164) .

**Comment by squeed** [comment]
Hah, nevermind! I misunderstood.

**Comment by mars1024** [comment]
@hongli-my  Friendly ping, any update on this?
