### ISSUE TITLE
Portmap shouldn't do anything if there aren't any ports to map

### ISSUE THREAD

**Issue by tmjd** [containernetworking/plugins#464]
I have heard, 2nd hand, that portmap can cause some iptables access issues in some cases with lots of services (like taking a long time when accessing or updating iptables). I was looking at the code and from what I can tell it always tries to read and possibly create the top level portmap chain(s), here https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/portmap.go#L100.

Is there any reason to always ensure that the top level chain is created, or could all iptables work be skipped if nothing needed to be configured for a specific portmap invocation?

**Comment by PavelSosin-320** [comment]
@greenpau
This is a repeating issue. There is a proposal to implement multi-backend portmap which can use both iptables and nftables but after a successful upgrade to podman 2.0.6 I found that such improvement doesn't produce significant added value because of:
1. All Linux distro used for running podman either have nft pre-installed or support nft. 
2. Following the [From iptables to nftables](https://wiki.nftables.org/wiki-nftables/index.php/Moving_from_iptables_to_nftables) It took me 5 minutes to convert iptables to nftables. The support of iptables looks like the legacy solution which will be used rarely as a fallback. If podman is a replacement of the docker in the future implementations it will be never used.

**Comment by bboreham** [comment]
@PavelSosin-320 I can't see that your comment is relevant to the question.

@tmjd I think your suggestion is good.  If the plugin doesn't need to do any work, it should just exit.
