### ISSUE TITLE
portmap plugin should include NEW state

### ISSUE THREAD

**Issue by baude** [containernetworking/plugins#467]
when using the port map plugin, if the default forward policy is to drop, traffic cannot reach the given container/port.  it is my understanding that NEW would fix this.  Without it, it seems like the portmap plugin is failing to do its basic job.

**Comment by baude** [comment]
@mccv1r0

**Comment by mccv1r0** [comment]
Portmap currently works if you try to connect to connect  from on the host itself.  e.g. assume the portmap plugin maps tcp:8080 in the host namespace to port 80 in a containers namespace, this will work:

```nc localhost 8080``` 

The ask is that when default policy for FORWARD chain is DROP, the portmap plugin should allow an external machine to connect  using a rule that is something along the lines of this:

```
iptables -A CNI-FORWARD -d $containerIP -p tcp --dport $containerPort -m state --state NEW  -j ACCEPT
```

since portmap is already adding rules for ```$containerIP``` already which allows traffic in the other direction.

**Comment by squeed** [comment]
We chatted about this at the maintainer's meeting. We're trying to decide if this should be fixed in the `portmap` or `firewall` plugin. The question is this: would the end-user expect that they should have to touch the firewall when forwarding ports, or should the act of forwarding ports be the signal that they want it open?

I'm leaning towards the latter - if you forward ports, you pretty clearly want them to be accessible. But I could be convinced to put this in the firewall plugin, too. It would consume it from the capability args.

**Comment by mars1024** [comment]
@squeed Just notice this recently, now firewall plugin only allow `RELATED,ESTABLISHED` traffic to come from outside, this means sometimes we can not **new** a network connection from outside even we enable the firewall plugin, so should we fix this?
