### ISSUE TITLE
bridge plugin should not disable IPv6 DAD in certain cases

### ISSUE THREAD

**Issue by dcbw** [containernetworking/plugins#52]
1) when hairpin mode is not enabled, DAD should not be disabled
2) when enhanced_dad is available in the kernel, that should be used instead of disabling DAD

**Comment by karampok** [comment]
We have similar issues:

Because of this [line](https://github.com/containernetworking/plugins/blob/20bc33abc565e75c0f9de488a020d1ef5b7d9b56/plugins/main/bridge/bridge.go#L299), the plugin errors. That file does not even exists in our only IPv4 stack.

It would also make sense to skip any IPv6 related tasks when the machine uses only IPv4.

**Comment by squeed** [comment]
@karampok filed separate issue #59

**Comment by squeed** [comment]
This is fixed.
