### ISSUE TITLE
host-device: interface moved back gets down after DEL was called

### ISSUE THREAD

**Issue by nakabonne** [containernetworking/plugins#754]
I moved an interface in a host's network namespace to container's one with the host-device plugin. The config is here:

```json
{
  "cniVersion": "0.4.0",
  "name": "mynet",
  "plugins": [
    {
      "type": "host-device",
      "device": "vcan0",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.10.0.0/16"
            }
          ]
        ]
      }
    }
  ]
}
```

The problem is that the interface moved back gets down after `DEL` was called.

**Before running a container**

```
❯ ip link show vcan0
31: vcan0: <NOARP,UP,LOWER_UP> mtu 72 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/can
```

**After running a container**

```
❯ ip link show vcan0
31: vcan0: <NOARP> mtu 72 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/can
    alias vcan0
```

It seems that the interface is left DOWN here. Do you think it is reasonable to call `LinkSetUp` at the end?

https://github.com/containernetworking/plugins/blob/9c59728d39b729558bb712c79e2c80acc0864191/plugins/main/host-device/host-device.go/#L264

**Comment by dcbw** [comment]
I guess it should balance the down/up calls... but when it's moved back to the main namespace, to be useful again, it would need to be configured, and presumably the thing that configures it needs to set it up anyway, right? eg if CNI was not in the picture at all, the thing that configures the interface would set it up.

I guess, I'm not sure what the actual issue is with the interface being down in the host namespace is. Could you elaborate more? Thanks!
