### ISSUE TITLE
Compiled plugins have unknown version

### ISSUE THREAD

**Issue by dilyanpalauzov** [containernetworking/plugins#758]
I call
```
$ git clone https://github.com/containernetworking/plugins
$ cd plugins
$ ./build_linux.sh
Building plugins 
  bandwidth
  firewall
  portmap
  sbr
  tuning
  vrf
  bridge
  host-device
  ipvlan
  loopback
  macvlan
  ptp
  vlan
  dhcp
  host-local
  static
$ bin/ptp --help
CNI ptp plugin version unknown
$ bin/ptp
CNI ptp plugin version unknown
```
* Plugins shall not report unsolicited that they do not know their version.
* The build process shall tell the compiled plugins their version.

**Comment by dcbw** [comment]
@dilyanpalauzov this is partly by design. The build version will be correctly inserted by the scritps/release.sh script that is run to product the official binaries provided as part of the CNI plugins releases.

However, not everyone will use the upstream release binaries. So we could add the same BUILDFLAGS logical that grabs the git tag or SHA and use that from build_linux.sh as well, then your custom downstream built binaries would also have the version.

Would you be willing to submit a PR that does this? I think we just want to move the BUILDFLAGS logic from scripts/release.sh to build_linux.sh and build_windows.sh?

**Comment by dilyanpalauzov** [comment]
Calling `./script/release.sh` does include the version in the plugins, but downloads first 100mb of OCI-images and builds the same plugins for countless platforms, leaving on Linux under bin/ the files host-local.exe, win-bridge.exe and win-overlay.exe. The plugins I want are not in the bin/ directory, but in `release-v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz`. That said I do not like calling `./script/release.sh`.

Ideally a version.h file shall be generated, if it is missing, and its content integrated in the binaries.

I am not going to submit any PR.
