### ISSUE TITLE
Create iptables rules without comments

### ISSUE THREAD

**Issue by DennisGaida** [containernetworking/plugins#820]
I see that all rules that are created in `iptables` receive comments, such as *CNI firewall plugin rules* 

and can be seen here: https://github.com/containernetworking/plugins/blob/main/plugins/meta/firewall/iptables.go.

When using the CNI plugins on a Unifi device with newest firmware, the unifi software complains about `iptables` rules that are unknown, specifically it complains about unknown comments, see here: https://github.com/unifi-utilities/unifios-utilities/issues/449

I currently don't know if possible, but it would be awesome to have a commentless-version of the CNI-plugins. As far as I can tell the comments are not necessary for the CNI rules to function. I don't know how we would be able to make this configurable (e.g. `-createruleswithoutcomment`).

Any ideas on how to implement this? Would it make sense to create two CNI versions - commentless and with comments? I could create my own fork without comments, but then again maybe it makes sense to do this here?

**Comment by squeed** [comment]
@DennisGaida interesting. ISTR that iptables "add"s and "deletes" need to match, including comments, but I'm not 100% certain about this. So, we can't just remove the comments, as it would break existing installations.

However, it could be an option on the cni plugin configuration passed down.

Note that some plugins require the comments for delete -- rather than trying to re-create the whole ruleset, they just delete any rules that have the given ID in the comment.

**Comment by ssbostan** [comment]
You can fork the repo, delete the comments and build your own version.
