### ISSUE TITLE
ipvlan can support muti-network policy? If not, any plan for this? 

### ISSUE THREAD

**Issue by jiayouseason** [containernetworking/plugins#973]
Unsure if ipvlan has a plan to support multi-network policy? 

https://docs.openshift.com/container-platform/4.14/networking/multiple_networks/configuring-multi-network-policy.html

**Comment by s1061123** [comment]
I suppose you're asking wrong place because ipvlan plugin does not care about multi-network policy because ipvlan plugin only cares to create ipvlan interface. In addition, you seems to be interested in OpenShift. OpenShift is commercial Kubernetes platform, maintained by Red Hat, hence if you are interested in the feature for OpenShift then please ask Red Hat. Here is open source community that maintains CNI plugin. This community does not maintain OpenShift (OpenShift utilizes this community product, but it does NOT mean this community handles OpenShift product).
